apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: practice
  labels:
    app: web
spec:
  replicas: 3 # 3つのPodを起動
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
