apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: practice
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # ブラウザでアクセスするポート
  type: NodePort
